alter table CPBM_TASK add constraint FK_CPBM_TASK_ON_PROC_INSTANCE foreign key (PROC_INSTANCE_ID) references BPM_PROC_INSTANCE(ID);
create index IDX_CPBM_TASK_ON_PROC_INSTANCE on CPBM_TASK (PROC_INSTANCE_ID);
